version: '3.8'

services:
  mineswepper-app:
    build: .
    container_name:
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run start
